mvp/outside/outside/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('frontend_auth.urls')),
    url(r'^', include('outside_listing.urls')),
]

mvp/outside/outside_listing/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from outside_listing import views
from django.contrib import admin


urlpatterns = patterns('',
                       url(r'^$', views.index, name="index"),
                       url(r'^map/$', views.map, name="map"),
                       url(r'^lead/(?P<id>[0-9]+)/$', views.lead_detail, name="lead-detail"),
                       url(r'^lead/(?P<id>[0-9]+)/closed/$', login_required(views.LeadClosedView.as_view()), name="lead-closed"),
                       url(r'^lead/(?P<id>[0-9]+)/repeat/$', login_required(views.LeadRepeatView.as_view()), name="lead-repeat"),
                       url(r'^lead/(?P<id>[0-9]+)/feedback/$', login_required(views.LeadFeedbackView.as_view()), name="lead-feedback"),
                       url(r'^admin/', include(admin.site.urls)),

                       )

mvp/outside/outside_listing/models.py
from django.db import models

# Create your models here.

mvp/outside/outside_listing/forms.py
# -*- coding: utf-8 -*-


from django import forms


class LeadClosedForm(forms.Form):
    proof = forms.CharField(required=True,
                            min_length=5,
                            max_length=512,
                            widget=forms.TextInput(attrs={'placeholder':u"Nachweis"})
                            )


class LeadRepeatForm(forms.Form):
    date = forms.DateTimeField(required=True, input_formats=['%d.%m.%Y %H:%M'], widget=forms.HiddenInput())
    comment = forms.CharField(required=False,
                            min_length=0,
                            max_length=2048,
                            widget=forms.Textarea(attrs={'placeholder':u"Kommentar (optional)"})
                            )

class LeadFeedbackForm(forms.Form):
    lost = forms.BooleanField(label="Kunde ist verloren",required=False)
    comment = forms.CharField(required=True,
                            min_length=5,
                            max_length=2048,
                            widget=forms.Textarea(attrs={'placeholder':u"Feedback / Begründung"})
                            )

mvp/outside/outside_listing/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from django.utils import timezone
from django.db.models import Q
from django.core.urlresolvers import reverse_lazy
from .forms import LeadClosedForm, LeadRepeatForm, LeadFeedbackForm
from frontend.models import Lead, ClosingEvent, Seller
from django.contrib.auth.decorators import login_required


def calculate_rev(request):
    ret = 0.0
    u = request.user
    for ce in u.closingevent_set.all():
        ret += ce.seller.reward
    # Reward minus 15% Service Fee
    return round(ret / 1.15,2)

# Create your views here.
@login_required
def index(request):
    ctx = {"leads": Lead.objects.all().order_by('created', 'lost', 'closed', '-repeat_at'),
           "rev": calculate_rev(request)}
    return render(request, 'outside_listing/index.html',ctx)

# Create your views here.
@login_required
def map(request):
    ctx = {"leads": Lead.objects.filter(lost=False, closed=False).filter(
        Q(repeat_at__lt=timezone.now()) | Q(repeat_at__isnull=True)).order_by('created', 'closed', '-repeat_at')
        , "rev": calculate_rev(request)}
    return render(request, 'outside_listing/lead_map.html',ctx)


@login_required
def lead_detail(request,id):
    ctx = {"lead": get_object_or_404(Lead, id=id),
           "rev": calculate_rev(request)}
    return render(request, 'outside_listing/lead_detail.html',ctx)


class LeadClosedView(FormView):
    template_name = 'outside_listing/lead_closed.html'
    form_class = LeadClosedForm
    success_url = reverse_lazy('index')



    def render_to_response(self, context, **response_kwargs):
        context['lead'] = get_object_or_404(Lead,id=self.kwargs.get('id'))
        context["rev"] = calculate_rev(self.request)
        return super(LeadClosedView, self).render_to_response(context,**response_kwargs)

    def form_valid(self, form):
        # Update Lead
        # TODO: Update User
        lead = get_object_or_404(Lead,id=self.kwargs.get('id'))
        lead.closed = True
        lead.lost = False
        lead.repeat_at = None
        lead.last_visited_at = timezone.now()
        lead.last_visited_by = self.request.user
        lead.save()

        # Create Closing Event
        # TODO: Update User
        # TODO: Figure out Seller
        c = ClosingEvent()
        c.user = self.request.user
        c.lead = lead
        c.seller = Seller.objects.last()  # TODO: Map these to users?
        c.proof = form.cleaned_data.get('proof')
        c.save()

        return super(LeadClosedView, self).form_valid(form)


class LeadRepeatView(FormView):
    template_name = 'outside_listing/lead_repeat.html'
    form_class = LeadRepeatForm
    success_url = reverse_lazy('index')



    def render_to_response(self, context, **response_kwargs):
        context["rev"] = calculate_rev(self.request)
        context['lead'] = get_object_or_404(Lead,id=self.kwargs.get('id'))
        return super(LeadRepeatView, self).render_to_response(context,**response_kwargs)

    def form_valid(self, form):
        # Update Lead
        # TODO: Update User
        lead = get_object_or_404(Lead,id=self.kwargs.get('id'))

        lead.repeat_at = form.cleaned_data.get('date')
        lead.comment = form.cleaned_data.get('comment')
        lead.lost = False
        lead.last_visited_at = timezone.now()
        lead.last_visited_by = self.request.user
        lead.save()

        return super(LeadRepeatView, self).form_valid(form)

class LeadFeedbackView(FormView):
    template_name = 'outside_listing/lead_feedback.html'
    form_class = LeadFeedbackForm
    success_url = reverse_lazy('index')



    def render_to_response(self, context, **response_kwargs):
        context["rev"] = calculate_rev(self.request)
        context['lead'] = get_object_or_404(Lead,id=self.kwargs.get('id'))
        return super(LeadFeedbackView, self).render_to_response(context,**response_kwargs)

    def form_valid(self, form):
        # Update Lead
        # TODO: Update User
        # TODO: Store Feedback Event?
        lead = get_object_or_404(Lead,id=self.kwargs.get('id'))

        lead.comment = form.cleaned_data.get('comment')
        lead.lost = form.cleaned_data.get('lost')
        lead.last_visited_at = timezone.now()
        lead.last_visited_by = self.request.user
        lead.save()

        return super(LeadFeedbackView, self).form_valid(form)

mvp/outside/outside_listing/templates/outside_listing/index.html
{% extends "base.html" %}

{% block title %}Outside{% endblock %}

{% block menu_index %}active{% endblock %}
{% block main %}

<div class="container">
    {% for lead in leads %}
    <div class="row b-b {% if lead.closed %}closed{% endif %} {% if lead.repeat_at %}repeat{% endif %} {% if lead.lost %}lost{% endif %}">
    <div class="col-xs-12">
    {% if not lead.closed and not lead.lost %}<a href="{{  url('lead-detail', id=lead.id) }}">{% endif %}
    <h3>{{ lead.name }}</h3>{% if not lead.closed %}</a>{% endif %}
        {% if lead.repeat_at %}<i class="fa fa-clock-o"></i> {{ lead.repeat_at }}<br/>{% endif %}
        {% if lead.closed %}<i class="fa fa-check-circle-o"></i> Abgeschlossen <br/>{% endif %}
        {% if lead.lost %}<i class="fa fa-frown-o"></i> Kunde verloren <br/>{% endif %}
    {{ lead.address }}
</div>

</div>

    {% endfor %}
</div>
{% endblock %}

mvp/outside/outside_listing/templates/outside_listing/lead_closed.html
{% extends "base.html" %}

{% block title %}Outside - {{ lead.name }}{% endblock %}

{% block main %}

    <div class="container">
        <div class="col-xs-12">
            <h1>{{ lead.name }}</h1>
            {{ lead.address }}
            <div class="alert alert-success">
                <h2>Verkauf bestätigen</h2>
                <form class="m-t" id="login" name="login" role="form" method="post">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="submit" class="btn btn-block btn-success block full-width m-b">BESTÄTIGEN
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mvp/outside/outside_listing/templates/outside_listing/lead_detail.html
{% extends "base.html" %}

{% block title %}Outside - {{ lead.name }}{% endblock %}

{% block main %}

    <style>
        html, body, .container-fluid, #map_canvas {
            height: 100%;
        }

        .container-fluid {
            width: 100%;

            top: 0;
            padding: 0;
        }

        #map_canvas {
            margin-top:20px;
        }
    </style>
    <div class="container">
        <div class="col-xs-12">
            <h1>{{ lead.name }}</h1>

            <p>
                {{ lead.address }}
            </p>

            <div class="row">
                <div class="col-xs-6"><p>{{ lead.phone }}</p></div>
                <div class="col-xs-6">
                    <p>
                        {% if lead.website %}
                            <!--<a href="{{ lead.website }}" target="_blank">Google</a>-->
                        {% endif %}
                        {% if lead.google_places_url %}
                            <a href="{{ lead.google_places_url }}" target="_blank"><i class="fa fa-external-link"></i>
                                Website</a>
                        {% endif %}
                    </p>
                </div>

            </div>
            <div class="row">
                <div class="col-xs-12">
                    {% if lead.comment %}
                        {{ lead.comment }}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">

                    <div class="btn-group-vertical btn-block" role="group">
                        <p>
                        <a href="{{ url('lead-closed',id=lead.id) }}" class="btn btn-success btn-block">VERKAUF
                            MELDEN</a>
                        <a href="{{ url('lead-repeat',id=lead.id) }}" class="btn btn-warning btn-block">SPÄTER
                            WIEDERHOLEN</a>
                        <a href="{{ url('lead-feedback',id=lead.id) }}" class="btn btn-danger btn-block">FEEDBACK EINGEBEN</a>
                        </p>
                    </div>
                </div>
            </div>


        </div>
    </div>
    <div class="container-fluid">
        <div id="map_canvas" class="map_canvas"></div>
    </div>

    <script>
        addLoadEvent(
                function () {
                    var mapDiv = document.getElementById("map_canvas");
                    /// Set control options for map
                    var zoptions = {
                        position: google.maps.ControlPosition.TOP_RIGHT,
                        style: google.maps.ZoomControlStyle.SMALL
                    };
                    /// Position of map using coord that were passed else do nothing.
                    var pos = new google.maps.LatLng({{ lead.lat }}, {{ lead.lng }});
                    /// Set basic map options using above control options
                    var options = {
                        zoom: 16,
                        zoomControlOptions: zoptions,
                        mapTypeId: google.maps.MapTypeId.TERRAIN,
                        center: pos,
                        draggable:false
                    };
                    this.map = new google.maps.Map(mapDiv, options);
                    var marker = new google.maps.Marker({
                        position:new google.maps.LatLng({{ lead.lat }}, {{ lead.lng }}),
                        map: map,
                        title: 'Hello World!'
                    });


                });
    </script>
{% endblock %}
{% block additional_js %}
    <script type='text/javascript'
            src="http://maps.googleapis.com/maps/api/js?sensor=false&extension=.js&output=embed"></script>
{% endblock %}

mvp/outside/outside_listing/templates/outside_listing/lead_feedback.html
{% extends "base.html" %}

{% block title %}Outside - {{ lead.name }}{% endblock %}

{% block main %}

    <div class="container">
        <div class="col-xs-12">
            <h1>{{ lead.name }}</h1>
            {{ lead.address }}
            <div class="">
                <h2>Feedback eingeben</h2>

                <form class="m-t" id="login" name="login" role="form" method="post">

                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="row">
                        <div class="col-xs-12">
                            <p>
                                <button type="submit" class="btn btn-block btn-danger block full-width m-b">FEEDBACK SPEICHERN
                                </button>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
     <script type="text/javascript">
                            //addLoadEvent();
                        </script>
    </div>
{% endblock %}
{% block additional_css %}

{% endblock %}
{% block additional_js %}

{% endblock %}

mvp/outside/outside_listing/templates/outside_listing/lead_map.html
{% extends "base.html" %}

{% block title %}Outside{% endblock %}

{% block menu_map %}active{% endblock %}
{% block main %}
    <style>
        html, body, .container-fluid, #map_canvas {
            height: 100%;
        }

        .container-fluid {
            width: 100%;

            top: 0;
            padding: 0;
        }

        #map_canvas {

        }
    </style>
    <div class="container">
        <!--
    {% for lead in leads %}
    <div class="row b-b {% if lead.closed %}closed{% endif %} {% if lead.repeat_at %}repeat{% endif %}">
    {% if not lead.closed  %}<a href="{{  url('lead-detail', id=lead.id) }}">{% endif %}
    <div class="col-xs-12">
    <h3>{{ lead.name }}</h3>
        {% if lead.repeat_at %}<i class="fa fa-clock-o"></i> {{ lead.repeat_at }}<br/>{% endif %}
    {{ lead.address }}
</div>
{% if not lead.closed %}</a>{% endif %}
</div>

    {% endfor %}
    -->
    </div>

    <div class="container-fluid">
        <div id="map_canvas" class="map_canvas"></div>
    </div>

    <script>
        addLoadEvent(
                function () {















                    var mapDiv = document.getElementById("map_canvas");
                    /// Set control options for map
                    var zoptions = {
                        position: google.maps.ControlPosition.TOP_RIGHT,
                        style: google.maps.ZoomControlStyle.SMALL
                    };
                    /// Position of map using coord that were passed else do nothing.
                    var pos = new google.maps.LatLng(0, 0);
                    /// Set basic map options using above control options
                    var options = {
                        zoom: 14,
                        zoomControlOptions: zoptions,
                        mapTypeId: google.maps.MapTypeId.TERRAIN,
                        center: pos,
                        draggable: true
                    };
                    this.map = new google.maps.Map(mapDiv, options);

                    {% for lead in leads %}
                        {% if not lead.closed %}

                    var pos = {lat: {{ lead.lat }}, lng: {{ lead.lng }}};

                    var contentString = '<div id="content">' +
                            '<div id="siteNotice">' +
                            '</div>' +
                            '{% if not lead.closed  %}<a href="{{  url('lead-detail', id=lead.id) }}">{% endif %}<h1 id="firstHeading" class="firstHeading">{{ lead.name }}</h1>{% if not lead.closed  %}</a>{% endif %}' +
                            '<div id="bodyContent">' +
                            '<p>{{ lead.address }}</p>' +
                            '<p>' +
                             '<div class="btn-group-vertical btn-block" role="group">' +
                        '<a href="{{ url('lead-closed',id=lead.id) }}" class="btn btn-success btn-block">VERKAUF MELDEN</a>' +
                        '<a href="{{ url('lead-repeat',id=lead.id) }}" class="btn btn-warning btn-block">SPÄTER WIEDERHOLEN</a>' +
                        '<a href="{{ url('lead-feedback',id=lead.id) }}" class="btn btn-danger btn-block">FEEDBACK EINGEBEN</a>' +
                    '</div>' +
                            '</p>' +
                            {% if lead.comment %}'<p>{{ lead.comment }}</p>' +{% endif %}
                            '<p><i class="fa fa-phone"></i> {{ lead.phone }} {% if lead.google_places_url %} <br/><a href="{{ lead.google_places_url }}" target="_blank"><i class="fa fa-external-link"></i> Website</a>{% endif %}</p>' +
                            '</div>' +
                            '</div>';

                    var infowindow{{ lead.id }} = new google.maps.InfoWindow({
                        content: contentString
                    });


                    var marker{{ lead.id }} = new google.maps.Marker({
                        position: pos,
                        map: map,
                        title: '{{ lead.name }}'
                    });
                    marker{{ lead.id }}.addListener('click', function () {
                        if (typeof currentwindow !== 'undefined') {
                            currentwindow.close();
                        }
                        currentwindow =infowindow{{ lead.id }};
                        infowindow{{ lead.id }}.open(map, marker{{ lead.id }});
                    });
                        {% endif %}
                    {% endfor %}

                    map.setCenter(pos);


                });
    </script>

    </div>
{% endblock %}
{% block additional_js %}
    <script type='text/javascript'
            src="http://maps.googleapis.com/maps/api/js?sensor=false&extension=.js&output=embed"></script>
{% endblock %}

mvp/outside/outside_listing/templates/outside_listing/lead_repeat.html
{% extends "base.html" %}

{% block title %}Outside - {{ lead.name }}{% endblock %}

{% block main %}

    <div class="container">
        <div class="col-xs-12">
            <h1>{{ lead.name }}</h1>
            {{ lead.address }}
            <div class="">
                <h2>Späteren Versuch festlegen</h2>

                <form class="m-t" id="login" name="login" role="form" method="post">
                    <div style="overflow:hidden;">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-8">
                                    <div id="datetimepicker12"></div>
                                </div>
                            </div>
                        </div>
                        <script type="text/javascript">
                            addLoadEvent(
                                    function () {
                                        $('#id_date').val(moment().add(1,'days').hours(0).minutes(0).seconds(0).locale('de').format('L HH:mm'));

                                        $('#datetimepicker12').datetimepicker({
                                            locale:'de',
                                            inline: true,
                                            sideBySide: false,
                                            keepOpen: true,
                                            minDate: moment().add(1,'days').hours(0).minutes(0).seconds(0).format(),
                                            maxDate: moment().add(1,'month').hours(0).minutes(0).seconds(0).format()
                                        });
                                        $('#datetimepicker12').on('dp.change', function(e) {
                                            $('#id_date').val($('#datetimepicker12').data().date);
                                        });
                                    });
                        </script>
                    </div>
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="row">
                        <div class="col-xs-12">
                            <p>
                                <button type="submit" class="btn btn-block btn-warning block full-width m-b">ERINNERUNG
                                    AKTIVIEREN
                                </button>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_css %}
    <link href="{{ static('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet"/>
{% endblock %}
{% block additional_js %}
    <script src="{{ static("js/moment.js") }}"></script>
    <script src="{{ static("js/bootstrap-datetimepicker.min.js") }}"></script>
{% endblock %}